const slash = ' / ';
const quit = "Quit";
const home = "Home";
const reset = "reset";
const retake = "Retake";
const review = "Review";
const result = "View Results";
const questions = "Questions";
const congratsMessage = "Congrats, Champ!";
const completionEntry = "Trivia complete";
const errorEntry = "Select an option to continue.";
const trivia = "Trivia";

const settings = "Settings";
const themeManager = "Theme";
const system = "System";
const light = "Light";
const dark = "Dark";
const dailyTrivia = "Daily Trivia";